n_trials: 20
sampler: "random"
metric: "f1"
direction: "maximize"
use_cv: false
cv_folds: 5

random_forest:
  n_estimators: { low: 50, high: 300 }
  max_depth: { low: 3, high: 15 }
  min_samples_split: { low: 2, high: 10 }
  min_samples_leaf: { low: 1, high: 5 }

logistic_regression:
  C: { low: 1.0e-3, high: 1.0e2 }
  solver: ["liblinear", "lbfgs"]
  penalty: ["l2"]
